### ISSUE TITLE
Missing themes

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [kartik-venugopal/aural-player#71] opened 2023-12-11 21:48 UTC
Best Mac player ever 😄

Version 3.25.0

I had all the themes go away apart from "Poolside". Tried removing "/Users/michaelzfreeman/Music/aural/state.json" but made no difference. Everything else seems to work.

**Comment by kartik-venugopal** [comment] 2023-12-14 21:41
Hi, thanks for the feedback and bug report.

Do you mean that you had created some custom themes and they disappeared ? Was there an app crash ? Or did you quit the app normally and they didn't reappear when you launched the app subsequently ?

Removing the state file would not help in this case.

Could you provide your aural.log file ? Maybe that has some clues.

**Comment by kartik-venugopal** [comment] 2024-01-13 10:41
Hi, without any further information (eg. logs, crash reports), I presume this a one-off case that I am unable to reproduce, so I am closing the issue for now.

If you can provide more info, I'd be happy to look into the issue further.

Cheers!

**Closed by kartik-venugopal** 2024-01-13 10:41 UTC
