### ISSUE TITLE
Improve FFmpeg error handling (I/O errors)

### ISSUE THREAD

**Issue by sirlaurie** [kartik-venugopal/aural-player#74] opened 2024-01-14 12:47 UTC
### Bug:

aural log file too big, it takes up most of space on my disk

<img width="231" alt="screenshot 4" src="https://github.com/kartik-venugopal/aural-player/assets/8928155/a2ad756a-ca19-4da1-9b8e-294928296c44">

### Reason:

I mount NFS drive on my macOS and use aural load music from NFS drive. when network disconnet, the NFS drive could not access by aural, it will generate error log constantly.

### Suggest:

1.  limit max size of log file
2. optimize file loading logic

**Comment by kartik-venugopal** [comment] 2024-01-14 22:27
Thanks for the bug report! Will take a look.

**Comment by kartik-venugopal** [comment] 2024-01-16 20:40
I did quite a bit of investigation and was able to reproduce the issue. This issue requires a carefully thought out solution in terms of error handling. I want to make sure to implement a reliable solution, so it will take me some time.

**Comment by sirlaurie** [comment] 2024-01-17 02:30
it's not hurry. maybe fix it in version 4.0?

**Comment by sirlaurie** [comment] 2024-06-09 14:01
Hi, sorry to bother, any news from 4.0?  can I build it from source? I am not a swift developer, and not familiar with building xcode project. It will be great if you provide a guide about how to build it from scratch😀

**Comment by kartik-venugopal** [comment] 2024-06-11 10:02
[Aural-4.0.zip](https://github.com/user-attachments/files/15786060/Aural-4.0.zip)

Hi @sirlaurie , I have attached a fresh new build of v4.0 for you. I have just not been able to release it yet because I've been extremely busy with other things, but I hope to release it in the next few months.

Please note that the attached app version is not complete ... some features will not work. There may be bugs or crashes, but the core features of it do work.

If you want to build it yourself in the future, all you have to do is download Xcode version 15.3, install the Command Line Tools 15.3, and then run Product > Archive and export a copy of the app.

You can also ask me for updated builds if you want. Cheers!

**Comment by kartik-venugopal** [comment] 2024-06-12 18:52
@sirlaurie - FYI, I have released a "preview" build of v4.0.0: [here](https://github.com/kartik-venugopal/aural-player/releases/tag/4.0.0-preview).

It has a few small fixes compared to the build I sent you earlier 😄

**Comment by sirlaurie** [comment] 2024-06-14 03:07
Wow, a big change! I noticed that "preview" release has fixed music loading bug. I have some wav file couldn't load successfully by aural before but can be played by ffplay, now it's all loaded successfully!

Love it!

**Comment by kartik-venugopal** [comment] 2024-12-18 23:42
Log file bloating fixed in preview21

**Closed by kartik-venugopal** 2024-12-18 23:42 UTC
