### ISSUE TITLE
Visualization window disappears if main window moves off initial display

### ISSUE THREAD

**Issue by brianredbeard** [kartik-venugopal/aural-player#59] opened 2023-06-14 18:06 UTC
When running in a multi-head environment the Aural visualization window fails to appear if the main window has been moved to a secondary monitor. It does not matter if the window is toggled via the keyboard shortcut or via "View -> Visualizer Window".

This is occurring on Ventura 13.4

**Comment by kartik-venugopal** [comment] 2023-06-15 18:57
Thanks for the bug report. I will look into it when I return to working on the project (away for a little while).

Cheers,
Kartik

**Comment by kartik-venugopal** [comment] 2023-09-16 21:40
Hi, I am unable to reproduce this issue on Ventura 13.3.1. Can you please list the exact sequence of steps, so I can be sure I'm not missing anything from your failure scenario ? Thanks!

**Comment by brianredbeard** [comment] 2023-09-19 00:29
In Ventura 13.5.2 (22G91) I was able to reproduce as follows:

First, to demonstrate the normal behavior:
1. Start Aural.
1. Using the "View" menu bar at the top of the screen, activate "Visualizer Menu"
<Visualizer window appears>

Next, to demonstrate aberrant behavior: 

1. Start Aural.
1. Drag the Aural to a different display
1. Using the "View" menu bar at the top of the screen, activate "Visualizer Menu"
<Visualizer window does not appear>

**Comment by brianredbeard** [comment] 2023-09-19 00:39
In fact, when trying to reproduce this (multiple times, each of which succeeded), i generated the following crash report:

[aural.dump.txt](https://github.com/kartik-venugopal/aural-player/files/12654435/aural.dump.txt)

**Comment by kartik-venugopal** [comment] 2023-10-01 19:51
Hi, I've looked at the crash report, but was not able to gain much insight from it. Also, I've been unable to reproduce on both Ventura 13.5.x and now 13.6.

Couple of ideas:

1 - Aural log file.

- With Aural NOT running, go into your Music folder and under the "aural" subfolder (where all the app state and log are stored), and delete "aural.log".
- Launch Aural and then run the error scenario with the visualizer to produce the crash (don't do anything else with the app, so that the log doesn't get bloated with unnecessary info).
- Grab the newly generated "aural.log" from the same location: ~/Music/aural/aural.log, and share it here with me.

2 - If the log file doesn't yield anything useful and if you are willing to try a little experiment, I can build a special app bundle for you augmented with some extra debugging statements put in, to generate extra log info to see at what exact point the crash occurs. Then you can repeat the above procedure and share the log file with me. This will definitely provide good insights into where the crash occurs and possibly why.

**Comment by kartik-venugopal** [comment] 2023-10-01 20:16
Also, can you please share details about your 2 displays: Manufacturer, model, resolution, etc. Which one is main and which one not ?

Is it a laptop connected to an external display ? Or an iMac / macMini ?

Or, at least, whether or not the 2 displays are identical in terms of resolution or not ?

**Comment by kartik-venugopal** [comment] 2024-01-13 10:43
Hello, without any further info, I am unable to reproduce this issue, so I am closing it for now.

If you can provide more info, I'd be happy to look into it further.

Cheers!

**Closed by kartik-venugopal** 2024-01-13 10:43 UTC
