### ISSUE TITLE
Gapless playback mode

### ISSUE THREAD

**Issue by yan-8** [kartik-venugopal/aural-player#90] opened 2024-07-06 20:46 UTC
Example in video.
I think much better do not have it.

https://github.com/kartik-venugopal/aural-player/assets/23197048/2b90620f-1ba7-4065-8e53-dc4f49d179f6

**Comment by kartik-venugopal** [comment] 2024-07-08 15:15
Hi, thanks for the issue report. I am aware of this issue, and it will most likely be fixed in v4. It is not easy to implement, but I will try my best 😄 

Cheers.

**Comment by kartik-venugopal** [comment] 2024-07-10 14:12
I have done extensive research and experimentation to achieve gapless playback. And I can confidently say that with the current implementation of AVAudioEngine, this is extremely difficult to achieve, and the result would not be worth the investment of effort and would mess up the code too much to be worth it.

If AVAudioEngine is enhanced in the future, I will definitely consider doing this.

**Comment by yan-8** [comment] 2024-07-10 20:03
Thank you for your effort. A bit sad, yep I mean that you did not find any fast solutions. I hope AVAudioEngine will help us in the future.

**Comment by kartik-venugopal** [comment] 2024-07-12 15:58
@yan-8 - I just thought of a way to implement this that would be possible, but only under certain some conditions:

There can be a special "gapless playback mode" which can be enabled when:

- All tracks in the play queue have the exact same audio format (and do not require audio engine reconfiguration between tracks). This will generally be true for tracks in the same album.
- The user agrees not to reorder or move any tracks around during playback. So, the order of tracks when playing would remain constant. 
- Sorting would now no longer be possible till playback is finished.
- Shuffling would not be available.
- All these ^ functions would again be available if/when the user stops playback.

I can do this. Should not be too difficult if done in this way. In any case, this will be done only in v4, not in v3 (the version you currently have).

What do you think ?

**Comment by yan-8** [comment] 2024-07-12 22:24
Thank you for your explanation, so interesting thoughts. 
May I ask a few questions about your conditions. So when this mode will be implemented and turned on, the user play its audio album like Pink Floyd - The Wall album where all tracks don’t have gaps.

"All tracks in the play queue have the exact same audio format (and do not require audio engine reconfiguration between tracks). This will generally be true for tracks in the same album."
-> As for me it sounds logically and intuitively.

"The user agrees not to reorder or move any tracks around during playback. So, the order of tracks when playing would remain constant."
-> Question - when user wants to make fast-forward or rewind, will it work?

"Sorting would now no longer be possible till playback is finished."
-> Question - what does it mean, sorting? You mean sorting files in playlist?

"Shuffling would not be available"
-> No problem.

"I can do this. Should not be too difficult if done in this way. In any case, this will be done only in v4, not in v3 (the version you currently have)."
-> As for me it looks good, I think that if you have an opportunity to implement this I think it is amazing. At least we will understand it when will try it.

-> Speaking about v4, may I ask, when are you planning to release v4 version? I am asking cause I saw some other visual or UI issues and I would report to you some of them if you don’t mind, what do you think? Or all these UI issues are independent on new v4 version?

**Comment by kartik-venugopal** [comment] 2024-07-13 08:25
Hey, thanks for the reply.

Yes, I mean let's say you play Pink Floyd The Wall, where there are no gaps, and you will not hear any gaps when this playback mode is enabled.

Yes, fast-forward and rewind will still work like before, no restrictions. Segment looping will not be available (looping part of a track). Repeating a single track (repeat one) will not be available, but "Repeat all" will be available.

Yes, by sorting, I mean sorting files in the playlist or "Play Queue" (in v4, it's called Play Queue)

About the v4 release, I have been really busy this year with personal things, so I am slowly doing little by little whenever I find time ... I am hoping by the end of this year :) But there is the preview release already available ... you can try it out, and I will keep updating the preview build over time.

**Comment by yan-8** [comment] 2024-07-13 12:33
Cool, thank you. I wish you inspiring and luck of it.

**Comment by kartik-venugopal** [comment] 2024-07-22 21:25
@yan-8 - I've implemented it, and it seems to be working well. I will do some final testing and give you a testable build soon (v4).

**Comment by yan-8** [comment] 2024-07-22 22:12
Great news. Thank you!

**Comment by kartik-venugopal** [comment] 2024-07-30 20:45
@yan-8 - I have released this feature in the preview3 build (check the latest release page, download the Zip from there).

Let me know how it works for you.
Cheers!

**Comment by yan-8** [comment] 2024-07-31 19:28
Nice, thank you! Will check it.

**Comment by LesterJitsi** [comment] 2024-08-04 16:37
I'm following all discussions here and installed preview 3. Right now I happened to listen, after a long time, to John Martyn's Live at Leeds CD** ripped in flac format. Well, I realized that it's been recorded without any gaps and so Aural plays it. What's odd is that the _Begin Gapless Playback_ is greyed out and not available, even though all requirements should be fulfilled. The same happens with all ripped CDs I tested, no matter the format.

**May this be related to original DAO recording instead of TAO? Thank you!

**Comment by kartik-venugopal** [comment] 2024-08-04 17:17
Hey @LesterJitsi , there are only 2 conditions required for the gapless playback menu item to be enabled:
1 - The player is not currently playing
2 - There are at least 2 tracks in the Play Queue.

Then, once you click the menu item, the only requirement is that all tracks must have exactly the same audio format, which will generally be true for all tracks in any album (if they came together as a set).

You must first stop the player, and then initiate Gapless Playback Mode. If it is stopped and it is still not enabled, let me know 😄

**Comment by LesterJitsi** [comment] 2024-08-04 17:41
To make it work I had to disable _After adding tracks, play first added tracks > If no track is currently playing_. It seems Aural doesn't care that no track is playing and starts to play anyway (I am dropping files over an empty Play Queue window). Stopping the player doesn't enable Gapless Playback Mode if the option above is checked.

**Comment by yan-8** [comment] 2024-08-04 20:50
Hey @LesterJitsi, how did you run "preview 3" version? I have a issue with it.

**Comment by LesterJitsi** [comment] 2024-08-05 11:37
@yan-8, I just installed in /Applications overwriting previous release and clicked on Aural icon in the Dock.

**Comment by yan-8** [comment] 2024-08-05 14:31
Strange, I did it couple times but still have a issue with it.

**Comment by LesterJitsi** [comment] 2024-08-05 15:37
Maybe that if the "issue" is disclosed a solution can be found...

**Comment by kartik-venugopal** [comment] 2024-08-05 16:12
> Strange, I did it couple times but still have a issue with it.

@yan-8  Can you please share your aural.log file with me ? I am not sure what issue you are facing. The log file can be found in ~/Music/aural

Thanks

**Comment by kartik-venugopal** [comment] 2024-08-05 16:18
@LesterJitsi - So if you want to drag an album into the Play Queue and play it gaplessly, do the following:
- Disable all autoplay settings
- Make sure that no tracks outside the album are in the Play Queue (either by choosing Replace behavior for drag-and-drop, or manually deleting other tracks)
- Click the Gapless Playback menu item (or keyboard: Alt+Space)

Since gapless playback mode imposes many restrictions on the app (described in above comments here), it is a special mode and by default, the app will choose normal playback mode so as not to restrict the user. Gapless Playback Mode must be initiated deliberately by the user on-demand.

**Comment by LesterJitsi** [comment] 2024-08-05 16:21
>  If you drag a bunch of files into the Play Queue and they begin playing, you cannot initiate gapless playback mode until you stop playback (with the Playback > Stop menu item or keyboard shortcut Cmd + .)

Thank you, most likely I was not clear. I got it right and I meant that even stopping the playback, the gapless mode menu item remains greyed out.

> To make it work I had to disable After adding tracks, play first added tracks > If no track is currently playing. It seems Aural doesn't care that no track is playing and starts to play anyway

This is the core of my issue, but maybe this is the intended behavior. Stopping the playback makes no difference. BTW, I'm reporting this only for debugging, as I don't think gapless mode will be relevant for me :wink:

**Comment by kartik-venugopal** [comment] 2024-08-05 16:23
@LesterJitsi - I see ... let me try to reproduce your issue. Can you send me a screenshot of your Playback preferences panel ?

**Comment by LesterJitsi** [comment] 2024-08-05 16:27
![Screenshot 2024-08-05 alle 18 25 01_1](https://github.com/user-attachments/assets/f2f8eaba-9494-49ca-8dd0-e377d4802046)

**Comment by kartik-venugopal** [comment] 2024-08-05 16:32
With that screenshot, the autoplay behavior you described is exactly as intended ... stopping it should enable the menu item, though 😄 

What "If no track is currently playing" means is ... only autoplay the first added track is nothing is currently playing. You said: " I had to disable After adding tracks, play first added tracks > If no track is currently playing. It seems Aural doesn't care that no track is playing and starts to play anyway (I am dropping files over an empty Play Queue window). "

So, if you mean this:
- The Play Queue is empty (meaning nothing is playing)
- You drag a bunch of files in
- It starts playing the first added file

This ^ is working exactly right in terms of autoplay.

But I cannot reproduce the menu item being disabled after stopping. Would you mind sending me a screen recording or the exact sequence of steps ? Because I'm not able to reproduce your issue.

**Comment by kartik-venugopal** [comment] 2024-08-05 16:35
> To make it work I had to disable _After adding tracks, play first added tracks > If no track is currently playing_. It seems Aural doesn't care that no track is playing and starts to play anyway (I am dropping files over an empty Play Queue window). Stopping the player doesn't enable Gapless Playback Mode if the option above is checked. _On app startup (if at least 1 track available)_ is permanently disabled.

I think you misunderstood what the option means ... the option is saying, if you already have something playing, it will not interrupt playback of what is already playing with something new. Only if nothing is currently playing, it will start playing what you have added.

I think you are interpreting this option to mean that it will only play the new thing if nothing is playing. That's the opposite of what this actually means.

**Comment by LesterJitsi** [comment] 2024-08-05 16:54
While recording the screen I got it at last: I was pausing the player instead of stopping it. Sorry  😊 Now it works of course.

> I think you misunderstood what the option means ... the option is saying, if you already have something playing, it will not interrupt playback of what is already playing with something new ... it will allow the already playing track to continue playing. Only if nothing is currently playing, it will start playing what you have added.

Yes, you're correct. Now I disabled all autoplay options. Thank you 😄 

Off topic, would it be possible to have the settings window to remember the last active panel? Just like in Safari, e.g. Is it just me or the settings window can not be closed with the usual shortcut ⌘W? I'm getting an error sound.

**Comment by kartik-venugopal** [comment] 2024-08-05 17:26
Cool, thanks 😄  Hmm, yeah, it is definitely possible to remember the last active pane ... I will implement that memory.

The settings window is currently modal ... I will make it non-modal 😁 

Cheers!

**Closed** 2024-08-05 17:30 UTC

**Comment by yan-8** [comment] 2024-08-11 20:27
> > Strange, I did it couple times but still have a issue with it.
> 
> @yan-8 Can you please share your aural.log file with me ? I am not sure what issue you are facing. The log file can be found in ~/Music/aural
> 
> Thanks

Hello, folder is empty.
![2024 08 11 - 22 26 19](https://github.com/user-attachments/assets/34fb84c9-aceb-494f-8d61-38555d30b8ad)

**Comment by kartik-venugopal** [comment] 2024-08-11 20:31
Can you try downloading the latest release ?

**Comment by yan-8** [comment] 2024-08-11 20:37
Sure.

**Comment by yan-8** [comment] 2024-08-11 20:53
It works, but help me please, how to turn on "Gapless Playback Mode"?
https://github.com/user-attachments/assets/38ca5018-2580-4085-825c-0c8c6e71bb17

**Comment by kartik-venugopal** [comment] 2024-08-11 21:21
![Screenshot 2024-08-11 at 11 20 09 PM](https://github.com/user-attachments/assets/a93215d7-59e5-4000-9280-5a7a288a4e3e)

**Comment by kartik-venugopal** [comment] 2024-08-11 21:21
NOTE - you must first completely stop the player (pausing is not enough), then go to that menu item.

**Comment by yan-8** [comment] 2024-08-11 21:56
Just run the player without music files, but I can't turn on it.
![2024 08 11 - 23 54 24](https://github.com/user-attachments/assets/46f9565f-9f45-4707-b0d4-bb06d0adb5ee)

**Comment by yan-8** [comment] 2024-08-11 21:56
or what is "completely stop the player"?

**Comment by kartik-venugopal** [comment] 2024-08-11 22:22
You must have at least 2 tracks in the play queue, and the player must be stopped (no track info is shown on the player window) ... not paused

Gapless playback mode begins when you click the menu item and ends when the album finishes playing

**Comment by kartik-venugopal** [comment] 2024-08-12 11:01
So here's what's required to do gapless playback:

- Clear the Play Queue so it has zero (0) tracks
- Disable Autoplay in Playback Preferences when adding tracks because Autoplay will initiate regular (not gapless) playback.
- Add your album to the Play Queue. All tracks must have the same audio format (this is generally true for albums).
- Playback > Begin Gapless Playback
