### ISSUE TITLE
Request: Menu item for "Simple player view main controls" or new default view and hide current default to be swappable on from menu

### ISSUE THREAD

**Issue by KalleNiemi** [kartik-venugopal/aural-player#49] opened 2023-01-04 07:30 UTC
Hey,

I'd love to see simpler main controls for player view that removes segment loop buttons and the L/R pan slider. Instead L/R slider, the volume slider could be longer.

I think this change could make for still clearer UI design by hiding two features that do not get used that often.

P.S. Great design; this is my 2nd day of using macOS and I found my favourite player to replace Winamp.

**Comment by kartik-venugopal** [comment] 2023-01-06 13:51
Hi @KalleNiemi , that's a great suggestion. 

In fact, the L/R slider has been moved (and the volume slider made longer) in v4.x, but this is definitely something that could be done now as well. And the segment loop button.

Just like in VLC, there could be a "simple controls" view or the simple view could be the default. Good idea.

Thanks for the great feedback. I will try to implement this soon.

Cheers !

**Comment by kartik-venugopal** [comment] 2023-01-24 19:23
Released in [v3.14.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.14.0).

Let me know if everything works as intended for you. Closing the issue in the meantime ...

Cheers !

**Closed by kartik-venugopal** 2023-01-24 19:23 UTC
Labels: in progress

**Comment by KalleNiemi** [comment] 2023-01-24 19:47
Absolutely perfect. Just installed, and how it looks and functions now is exactly how I imagined it could be with what I requested!
