### ISSUE TITLE
Huge log file

### ISSUE THREAD

**Issue by poeti8** [kartik-venugopal/aural-player#108] opened 2024-09-22 07:38 UTC
I opened my Music folder today and saw that the aural folder contains a 9GB log file (`Users/myuser/Music/aural/aural.log`). I'm not sure if I have enabled a debug mode, I don't find such option on settings panel right now.

Here's the last 50 lines from that file:
```
[dsf @ 0x11f0ad800] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[dsf @ 0x1078a2200] Stream #1: not enough frames to estimate rate; consider increasing probesize
[dsf @ 0x1078a2200] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x1078a2200] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2024-09-22 07:35:45.801 Aural[49905:5212600] Event tap creation failed: is your application sandboxed?
[dsf @ 0x13d02c200] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x13bc20200] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x11bca9000] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x11c041400] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x11c82a400] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x290829400] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x13c0ac000] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x11d044e00] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x13c4b8000] Estimating duration from bitrate, this may be inaccurate
2024-09-22 07:56:27.869 Aural[50649:5231901] Event tap creation failed: is your application sandboxed?
2024-09-22 08:22:51.502 Aural[53349:5259711] Event tap creation failed: is your application sandboxed?
2024-09-22 08:26:01.468 Aural[53552:5262819] Event tap creation failed: is your application sandboxed?
[flac @ 0x12dc32e00] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[flac @ 0x12e808200] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[flac @ 0x12b85c400] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[flac @ 0x12c060400] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[flac @ 0x12b864800] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[flac @ 0x15c808200] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[flac @ 0x12b864800] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2024-09-22 08:50:40.657 Aural[55502:5285974] Event tap creation failed: is your application sandboxed?
[flac @ 0x122d54600] Discarding ID3 tags because more suitable tags were found.
[flac @ 0x12000a600] Discarding ID3 tags because more suitable tags were found.
[flac @ 0x122d54600] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[flac @ 0x1242e8600] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[flac @ 0x12000b600] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[flac @ 0x12000b600] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2024-09-22 10:26:55.196 Aural[59864:5333515] Event tap creation failed: is your application sandboxed?
[flac @ 0x125056c00] Discarding ID3 tags because more suitable tags were found.
2024-09-22 10:52:52.415 Aural[61371:5358253] Event tap creation failed: is your application sandboxed?
2024-09-22 11:01:00.495 Aural[61371:5364624] Failed to scrobble track 'Dean Blunt - Demon' on Last.fm. Error: The request timed out.
2024-09-22 11:05:08.986 Aural[61371:5367814] Failed to scrobble track 'Dean Blunt - Flaxen' on Last.fm. Error: The request timed out.
2024-09-22 11:05:59.036 Aural[61371:5368339] Failed to scrobble track 'Dean Blunt - V' on Last.fm. Error: The request timed out.
```

**Comment by kartik-venugopal** [comment] 2024-09-22 22:35
Hi, thanks for the issue report.

1 - Which version of the app are you using ? Aural > About Aural
2 - How long have you been using the app ?
3 - Did you have any recent troubles with the app ? A crash or freeze or trouble reading some files ?

**Comment by poeti8** [comment] 2024-09-23 09:30
1. 3.25.1
2. Could be almost a year.
3. Nope nothing that I can remember. 
4. I inspected the last 1,000,000 lines and this error was almost all of it. It kept repeating, I don't know how far I could go back but it wouldn't end. It must be millions of lines:

```
// ... continues
2024-08-06 12:44:49.302 Aural[73796:47668820] Decoder error while reading track /Volumes/music/songs ohia/[2001] - Mi sei apparso come un fantasma [Live]/02 Nobody Tries That Hard Anymore.flac : Aural.PacketReadError
2024-08-06 12:44:49.302 Aural[73796:47668820] Unable to read packet. Error: -5 (Input/output error))
2024-08-06 12:44:49.302 Aural[73796:47668820] Decoder error while reading track /Volumes/music/songs ohia/[2001] - Mi sei apparso come un fantasma [Live]/02 Nobody Tries That Hard Anymore.flac : Aural.PacketReadError
2024-08-06 12:44:49.302 Aural[73796:47668820] Unable to read packet. Error: -5 (Input/output error))
// ... continues
```

All the timestamps where in the same second, only milliseconds apart. `/Volumes/music` Is the external hard drive I use. I suspect that the file was still in the aural playlist but the hard drive was ejected.

There were some other repeating lines at the end of the file but they didn't take space as much. 10–50 lines or so each time they appear:

```
[flac @ 0x10c817600] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```

```
[flac @ 0x116816e00] Discarding ID3 tags because more suitable tags were found.
```

```
[dsf @ 0x11f80ee00] Stream #1: not enough frames to estimate rate; consider increasing probesize
[dsf @ 0x11f80ee00] Estimating duration from bitrate, this may be inaccurate
[dsf @ 0x11f4b7c00] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
```

```
[iff @ 0x14453a600] Estimating duration from bitrate, this may be inaccurate
```

**Comment by kartik-venugopal** [comment] 2024-09-23 10:14
Thanks again for the info!

From the recent log you sent me, it is clear what the issue is, and it is the same as another issue previously filed, so I am aware of the cause: https://github.com/kartik-venugopal/aural-player/issues/74

What basically happens is, with non-native files (such as FLAC, DSF, Opus, etc), when there is trouble reading the file, for example, when a network drive or USB drive gets disconnected, FFmpeg keeps trying to read it without success. Unfortunately, the fix for this will require some deeper investigation. Luckily, it is a relatively rare event so unless you have an external network / USB drive that frequently gets disconnected, it most likely won't ever happen.

I must tell you - v3 is in archived status at this point, so there will be no further work or releases on it. The fix will go into v4 (coming later).

My suggestion for now - If you notice a drive disconnection, just check the log size and delete it if it's too big for you.

Hope this works for now ?

I am closing this issue because it is a duplicate of https://github.com/kartik-venugopal/aural-player/issues/74, but you are of course welcome to continue posting updates / replying to this issue.

**Closed by kartik-venugopal** 2024-09-23 10:14 UTC

**Comment by poeti8** [comment] 2024-09-23 11:22
> Does your external hard drive get disconnected often ? Would this be a regular occurrence for you ?

Yes, although the occurrence itself should be rare since I wouldn't keep a track from my external hard drive on my playlist if it's not connected. It's not a big deal anyway, as you mentioned I'll just delete the file if I notice it gets big. I just wanted to report this to let you know.
